{% set name = "Metview" %}
{% set version = "5.8.1" %}

package:
  name: metview-batch
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/3964985/{{ name }}-{{ version }}-Source.tar.gz
  sha256: dee81efb6e3127457e47c6722b468e4ff1c27f647ea46f98950d46402bed81f8
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0006-Pass-CPP-to-rpcgen.patch

build:
  number: 4
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libcurl
    - eccodes >=2.17.0
    - magics-metview-batch >=4.3.0
    - boost
    - flex
    - bison
    - libnetcdf
    - proj
    - gdbm
    - fftw
    - _openmp_mutex  # [linux]
  run:
    - libcurl
    - eccodes >=2.17.0
    - magics-metview-batch
    - flex
    - bison
    - libnetcdf
    - proj
    - gdbm
    - fftw
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
  run_constrained:
    # metview-batch is incompatible with metview
    - metview ==9999999999

test:
  commands:
    - test -f $PREFIX/lib/metview-bundle/lib/libMvMacro${SHLIB_EXT}
    - test -f $PREFIX/lib/metview-bundle/bin/metview_bin/uPlotBatch
    - test -f $PREFIX/lib/metview-bundle/bin/metview_bin/XSection
    - test -f $PREFIX/bin/metview

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache-2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: "ECMWF Metview Copyright 2007-2020 ECMWF."

extra:
  recipe-maintainers:
    - iainrussell
    - StephanSiemen
    - sandorkertesz
