{% set name = "Metview" %}
{% set version = "5.10.0" %}

package:
  name: metview-batch
  version: {{ version }}

source:
  url: https://confluence.ecmwf.int/download/attachments/30048389/{{ name }}-{{ version }}-Source.tar.gz
  sha256: e323a1ab39ecf5a619acc6f0b8986b9f0ed6e1a024b23383a64f02f6b631379b
  patches:
    - 0001-Use-find_package-instead-of-find_library-for-threads.patch
    - 0002-Pass-CPP-to-rpcgen.patch

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libcurl
    - eccodes >=2.19.0
    - magics-metview-batch >=4.5.0
    - boost
    - flex
    - bison
    - libnetcdf
    - proj
    - gdbm
    - fftw
    - _openmp_mutex  # [linux]
    - openlibm  # [osx]
  run:
    - libcurl
    - eccodes >=2.19.0
    - magics-metview-batch >=4.5.0
    - flex
    - bison
    - libnetcdf
    - proj
    - gdbm
    - fftw
    - llvm-openmp  # [osx]
    - _openmp_mutex  # [linux]
    - openlibm  # [osx]
  run_constrained:
    # metview-batch is incompatible with metview
    - metview ==9999999999

test:
  commands:
    - test -f $PREFIX/lib/metview-bundle/lib/libMvMacro${SHLIB_EXT}
    - test -f $PREFIX/lib/metview-bundle/bin/uPlotBatch
    - test -f $PREFIX/lib/metview-bundle/bin/XSection
    - test -f $PREFIX/bin/metview

about:
  home: https://confluence.ecmwf.int/display/METV/
  license: Apache-2.0
  license_family: Apache
  license_file: metview/LICENSE
  summary: ECMWF Metview Copyright 2007-2020 ECMWF.

extra:
  recipe-maintainers:
    - iainrussell
    - StephanSiemen
    - sandorkertesz
